### ISSUE TITLE
The model for repressor

### ISSUE THREAD

**Issue by yamamotoryo** [quadbiolab/Pando#20]
Hi @joschif ,

Thank you for creating a great tool. I've got interesting findings so far using Pando.
I have a question about the model predicting target gene expression.
As far as I know, repressors close the target chromatin when they work (DOI: [10.1016/j.cell.2015.07.048](https://doi.org/10.1016/j.cell.2015.07.048), DOI: [10.1016/j.celrep.2019.10.106](https://doi.org/10.1016/j.celrep.2019.10.106)), so the model 
Expression of repressor * Accessibility of the target region
might not reflect the activity of the repressor.
    
Expression of repressor * (1-Accessibility of the target region) 
(if we scale the accessibility to 0–1)
would be an idea.

What do you think about this?

Best,
Ryosuke

**Comment by joschif** [comment]
Hi @yamamotoryo,

yes I think broadly speaking I agree with you. If the TF is strictly a repressor that works by closing the chromatin, then this is something that Pando currently does not capture well. The implicit assumption is that TF activity is correlated with the accessibility of the binding site. It's also hard to delineate on the level of TFs, since many TFs can be activating and repressing and the context is not known a priori. However, there might be a way of better annotating genomic regions and their relation to the target gene before fitting the model. Then accessibility of repressive regions could be treated in the model similar to what you proposed. 

I definitely think this would be a great idea for future versions and fits with some ideas I had on my list :)

Best,
Jonas
