### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by longfeili5170** [quadbiolab/Pando#3]
Hi,
Is there any suggestion about visualization？
Thanks!

**Comment by joschif** [comment]
Hi @longfeili5170, we have explored some graph visualizations in our [manuscript](https://www.biorxiv.org/content/10.1101/2021.08.24.457460v1.full.pdf), but so far I have not implemented those in Pando. This is mainly because I have not found anything yet that consistently works well and is informative. In my experience the best choice of visualization is very dependent on the surrounding analysis and the context. I'll for sure add some options in the future though, so stay tuned :)

**Comment by longfeili5170** [comment]
Thanks again!
